field: 021dc031-5726-4bf4-808e-53a9d3c50ab2 # Buttons
fieldLayouts:
  9b0578a6-7039-4608-814f-a1d49936a7b0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 92b602c5-a12a-4516-a436-f4a79378b6b6 # Button Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51eae3d1-7e6d-4a13-ba64-e2e77f88c7e0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a0d62df1-44e1-4caf-9866-5bf2b280444f
        userCondition: null
fields:
  92b602c5-a12a-4516-a436-f4a79378b6b6: # Button Link
    columnSuffix: xpfwjtng
    contentColumnType: text
    fieldGroup: null
    handle: buttonLink
    instructions: null
    name: 'Button Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: arrowButton
name: 'Arrow Button'
sortOrder: 2
