field: 85957093-f7ea-4029-a94b-b1a4da04c318
fieldLayouts:
  adaf9e64-733c-4c46-89ad-6c5bec0bf01d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 43f9dbe1-a2b3-47e3-92df-7be878d7367c # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40c697b2-ec14-4501-8336-1c1756477609
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7f08e263-a49f-4714-a5af-252c205d57c1 # Background Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f9576e7-468d-4ba8-8edb-7f4690f29b11
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 62dc53f2-551e-4e65-b93d-c23b711e6aac
        userCondition: null
fields:
  7f08e263-a49f-4714-a5af-252c205d57c1: # Background Video
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: backgroundVideo
    instructions: null
    name: 'Background Video'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - video
      branchLimit: null
      defaultUploadLocationSource: 'volume:b06f7d5b-f09a-4ddf-b77f-dc89f56a7419' # Background Videos
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:76d72b7b-bcd8-4f9a-807e-905a9c11c83e' # Can Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  43f9dbe1-a2b3-47e3-92df-7be878d7367c: # Background Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: backgroundImage
    instructions: null
    name: 'Background Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:5bde54d0-f163-4aff-82a7-fb8f3d0066a5' # Background Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:76d72b7b-bcd8-4f9a-807e-905a9c11c83e' # Can Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: background
name: Background
sortOrder: 4
