field: a5788732-8476-446d-b6ed-04f8cc7d9c00 # Awards
fieldLayouts:
  a731ed6a-1909-4b32-bf49-cfc189d6b579:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1f5c806d-338d-4b1f-bf82-3680d1d7fbaf # Award Year
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b757a9d-421c-4b2d-8285-f8b129ca8717
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 164cf5ba-20a0-4835-aada-5d84eb1661b8 # Award Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5874737-9f96-4425-a29b-45c42bf89c11
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0b65d550-c2fa-4cf3-8b2b-740c61b746cb
        userCondition: null
fields:
  1f5c806d-338d-4b1f-bf82-3680d1d7fbaf: # Award Year
    columnSuffix: yxrhhnds
    contentColumnType: integer(10)
    fieldGroup: null
    handle: awardYear
    instructions: 'What year was this award won?'
    name: 'Award Year'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  164cf5ba-20a0-4835-aada-5d84eb1661b8: # Award Name
    columnSuffix: ajekvbbz
    contentColumnType: text
    fieldGroup: null
    handle: awardName
    instructions: 'What is the name of the award?'
    name: 'Award Name'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: bronzeAward
name: 'Bronze Award'
sortOrder: 3
