field: 85957093-f7ea-4029-a94b-b1a4da04c318
fieldLayouts:
  230a76c5-c68b-4375-b4b0-86d60fe6d113:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 98806770-54d6-40e5-a88c-d8c5af972ee9 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c64da4f5-05fd-4dd2-98f2-c8ef48954784
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e4ed0436-8bb7-49f2-bfb7-5906aa0b9734
        userCondition: null
fields:
  98806770-54d6-40e5-a88c-d8c5af972ee9: # Description
    columnSuffix: ticsyfto
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: Description
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: description
name: Description
sortOrder: 2
