field: 85957093-f7ea-4029-a94b-b1a4da04c318
fieldLayouts:
  a20fb6ef-5b34-4add-a553-5adec75e70ce:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cfc8675b-6656-4bc0-8889-b63d80b4c1d9 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b23ca6ca-ffd1-4768-b7ee-e22d92c5825b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3f52c0ec-d946-4345-b37c-b2b00dda5201
        userCondition: null
fields:
  cfc8675b-6656-4bc0-8889-b63d80b4c1d9: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:db9d70f0-8392-4fbe-801f-9deeb6f7a968' # General Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:76d72b7b-bcd8-4f9a-807e-905a9c11c83e' # Can Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 1
