field: 25c6a98b-d119-4ae1-8d5f-e0a804ac1448 # Series Toggle
fieldLayouts:
  1ddc6902-ea72-454a-a63e-82d25df1c984:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ef14b30a-e09c-44a2-abf7-37e5265430f3 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf34602a-9cfd-4b5e-8e89-687ca0caf109
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dbc09702-58fb-406b-bb8e-d71fd7c5159d
        userCondition: null
fields:
  ef14b30a-e09c-44a2-abf7-37e5265430f3: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:db9d70f0-8392-4fbe-801f-9deeb6f7a968' # General Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:76d72b7b-bcd8-4f9a-807e-905a9c11c83e' # Can Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 1
