field: 8dbf61b7-8e71-4013-8e45-0e1e3f0d5922 # Social Link
fieldLayouts:
  0cee3897-4526-459a-bd64-62df9e9662e7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e2c0d4de-9225-40c7-8a32-f7de10a7aaa8 # Link URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 878983de-66b5-4ffb-8335-d224e3eb2241
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a0d37d8d-0a19-49ba-ba60-cf035bf5ec1a # Channel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff3a198b-4f1a-4fa5-be6c-17dc5f50f230
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1c35adcb-92b8-4e98-b482-3118517e5b8c
        userCondition: null
fields:
  a0d37d8d-0a19-49ba-ba60-cf035bf5ec1a: # Channel
    columnSuffix: sjrgmvbv
    contentColumnType: string(9)
    fieldGroup: null
    handle: channel
    instructions: null
    name: Channel
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - Facebook
            -
              - value
              - facebook
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Instagram
            -
              - value
              - instagram
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - LinkedIn
            -
              - value
              - linkedin
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - X
            -
              - value
              - x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Spotify
            -
              - value
              - spotify
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  e2c0d4de-9225-40c7-8a32-f7de10a7aaa8: # Link URL
    columnSuffix: xbwebvwg
    contentColumnType: string(255)
    fieldGroup: null
    handle: linkUrl
    instructions: null
    name: 'Link URL'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: link
name: Link
sortOrder: 1
