field: a5788732-8476-446d-b6ed-04f8cc7d9c00 # Awards
fieldLayouts:
  75891f50-c7b6-4155-9dbc-47e19ad5988c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a2b39e67-8244-49b2-9f7c-6b185bd3042f # Award Year
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7dacde0a-1f3a-4f0d-a8e1-04d07432c686
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cde561fa-f273-48e3-ba47-db9fc49ecbe8 # Award Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: defc1498-d071-4be7-beaa-0ca9ff40c47c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1cb83dfe-e97c-4a2f-b454-4fc28e5a1c23
        userCondition: null
fields:
  a2b39e67-8244-49b2-9f7c-6b185bd3042f: # Award Year
    columnSuffix: vnvxhrxr
    contentColumnType: integer(10)
    fieldGroup: null
    handle: awardYear
    instructions: 'What year was this award won?'
    name: 'Award Year'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: null
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  cde561fa-f273-48e3-ba47-db9fc49ecbe8: # Award Name
    columnSuffix: fzfkddjs
    contentColumnType: text
    fieldGroup: null
    handle: awardName
    instructions: 'What is the name of the award?'
    name: 'Award Name'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: silverAward
name: 'Silver Award'
sortOrder: 2
