fieldLayouts:
  f4fb0002-f0f0-41bf-8ead-3ab6418ade1d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b1053d21-14e5-4009-ac5e-8605bda3f474
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 612bfd79-519c-4db3-9ad9-3df56af2b354 # Landing Section
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe60f1ae-1e8e-494e-aa16-36552b626c47
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: aa91b112-1ec9-43b0-9253-7e4c9757faf7
        userCondition: null
handle: beerFinder
hasTitleField: true
name: 'Beer Finder'
section: 1f34453a-cacc-4c27-a515-05b3a89f5b76 # Locations
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
