color: null
fieldLayouts:
  0cee3897-4526-459a-bd64-62df9e9662e7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e2c0d4de-9225-40c7-8a32-f7de10a7aaa8
            handle: null
            includeInCards: true
            instructions: null
            label: 'Link URL'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 878983de-66b5-4ffb-8335-d224e3eb2241
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a0d37d8d-0a19-49ba-ba60-cf035bf5ec1a
            handle: null
            includeInCards: false
            instructions: null
            label: Channel
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff3a198b-4f1a-4fa5-be6c-17dc5f50f230
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1c35adcb-92b8-4e98-b482-3118517e5b8c
        userCondition: null
handle: link
hasTitleField: false
icon: null
name: Link
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
