fieldLayouts:
  06709d24-329f-4696-bd57-5723f8ae47ef:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1a177c2f-a1d7-46cf-94fe-5063e37a8834
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 612bfd79-519c-4db3-9ad9-3df56af2b354 # Landing Section
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c965c0ac-c93e-42d9-b26f-b01a05fa3504
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1d42debc-f311-4702-b75a-37951c101737 # Card Slider
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 415e3de5-be85-4772-92fb-fe3a3e1afb9c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2aaf1fd0-574c-4f5c-b9d4-f57bed787033
        userCondition: null
handle: ourApproach
hasTitleField: true
name: 'Our Approach'
section: 76a1851c-73ea-4eb1-8e0d-a7501be656b0 # About
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 5
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
