fieldLayouts:
  c26bcb44-d9fb-475b-a015-49d5662cac5a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dc2304e4-39c7-4f10-9e14-22cccef58ec8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 612bfd79-519c-4db3-9ad9-3df56af2b354 # Landing Section
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70d5fc74-e779-471e-87fa-96e7f739dc10
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0975165c-a86d-4411-b78e-cc95b836001f
        userCondition: null
handle: ourAwards
hasTitleField: true
name: 'Our Awards'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
