defaultPlacement: end
fieldLayouts:
  a1f38453-c7c8-488e-8809-1572095c21b9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 80befecf-5945-4819-ba69-0fc7cb8bed62
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ad02cc6a-65c1-461f-a44b-2675bdcd2625 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d70c08c1-0c5f-4e4f-aa09-823594e54144
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: 20b27f26-ecf9-4142-bce5-e2b55811759e
            userCondition: null
            warning: null
          -
            elementCondition: null
            fieldUid: bffc7c3c-02c7-46d1-9835-a9096a16f727 # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0bb77dfa-9930-4110-82eb-f5ba7559a0fb
            userCondition: null
            warning: null
            width: 100
          -
            attribute: newWindow
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            orientation: null
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\NewWindowField
            uid: 01393790-decf-4b81-8aac-0a8130432daf
            userCondition: null
            warning: null
            width: 100
        name: Node
        uid: ff1158f7-f6ea-437a-9a99-87e012065e34
        userCondition: null
handle: header
instructions: 'This is where you can add navigation links and structure'
maxNodes: null
name: Header
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
propagationMethod: all
siteSettings:
  35d5050e-3d8c-448a-8ed5-1a9eaba13e13: # Melvin Brewing
    enabled: true
sortOrder: 1
structure:
  maxLevels: null
  uid: 581a013d-6606-4c5d-b33b-6f878be9c2e2
