baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Melvin Brewing'
primary: true
siteGroup: d9712e97-c935-48f3-8b44-f3ce6e52d842 # Melvin Brewing
sortOrder: 1
