childBlocks: null
conditions: null
description: ''
enabled: true
field: 10e9a8b2-c801-433b-82f1-4bfddf3231af # Page Sections
fieldLayouts:
  1ce8b015-0b50-4b83-9c7a-b5386e08e20f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bffc7c3c-02c7-46d1-9835-a9096a16f727 # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba04867e-7779-4c35-90ce-36d8bfd59247
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a11615b2-853a-4fe3-9dd7-99901084d23e # Background Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97ee8357-f8fc-48dc-bd8d-c682f0d09d01
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0446437e-7c98-4974-8103-766d4249c7e3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 13504266-15af-46cc-abf9-80c9136fa83b # Background Overlay
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ec5dcfb-8b79-4f4a-bd1c-e2aaf36fd191
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3c09f8e7-d651-4b43-9478-d543321de483 # Background Size
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24984da5-2bd7-4470-a9a2-df34a809f73f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a111ef49-544a-4868-b0aa-c9f69bffffd1 # Height
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63693f88-0a71-4529-9446-974715734860
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: cc8d9600-d589-4687-bd53-e93f7902d72d
        userCondition: null
group: null
groupChildBlockTypes: true
handle: background
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Background
topLevel: false
