childBlocks: null
conditions: null
description: 'Add a background image or video. If you select a video, it will take precedence over the image and display instead.'
enabled: true
field: 537b387e-676e-45bc-8784-94ab111fecb8 # Series Landing Section
fieldLayouts:
  14f25552-f066-453c-b9e6-04965d01dac1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bffc7c3c-02c7-46d1-9835-a9096a16f727 # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ccefdf4c-e395-4c9b-a5cf-8e6b3c018f70
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a11615b2-853a-4fe3-9dd7-99901084d23e # Background Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2782fbf6-2c11-440b-995e-501d634a5f3c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cd4f90ca-9f83-4f70-b4e1-7e24be45aef3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 13504266-15af-46cc-abf9-80c9136fa83b # Background Overlay
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea5e27a9-1043-47e4-8582-732758b59300
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: e726bee3-f659-4fbe-9acf-61aef507e858
        userCondition: null
group: null
groupChildBlockTypes: true
handle: background
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 1
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Background
topLevel: true
