childBlocks: null
conditions: null
description: 'Add a button.'
enabled: true
field: 537b387e-676e-45bc-8784-94ab111fecb8 # Series Landing Section
fieldLayouts:
  09047780-f981-4bc7-a9c0-c533d1c7e1e7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 021dc031-5726-4bf4-808e-53a9d3c50ab2 # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd5e3097-c89f-43c8-8a2c-3cb97b416ff3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8d0330b8-8cfc-4ed5-a9cc-0d12a74ae534
        userCondition: null
group: null
groupChildBlockTypes: true
handle: buttons
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 1
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Buttons
topLevel: true
