childBlocks: null
conditions: null
description: ''
enabled: true
field: 10e9a8b2-c801-433b-82f1-4bfddf3231af # Page Sections
fieldLayouts:
  a8a74077-5f94-4592-9c58-5f6ea1342fc8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 021dc031-5726-4bf4-808e-53a9d3c50ab2 # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6bd77b46-6493-404c-adb3-f280d6d16def
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d319ba9d-ac9d-4618-8cb5-a4b7132d36dc
        userCondition: null
group: null
groupChildBlockTypes: true
handle: buttons
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Buttons
topLevel: false
