childBlocks: null
conditions: null
description: ''
enabled: true
field: 5626309f-5327-4844-a153-344a113be872 # Location Toggle
fieldLayouts:
  4bf05f3f-9386-4e72-b175-e2683805fc3b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ad02cc6a-65c1-461f-a44b-2675bdcd2625 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0331ed20-d6b7-425f-9341-33982e2ff6eb
            userCondition: null
            warning: null
            width: 100
        name: Description
        uid: 3efb40c5-0f3a-4d7b-9475-7b06b28be94e
        userCondition: null
group: null
groupChildBlockTypes: true
handle: description
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Description
topLevel: true
