childBlocks: null
conditions: null
description: ''
enabled: true
field: 10e9a8b2-c801-433b-82f1-4bfddf3231af # Page Sections
fieldLayouts:
  338d23a6-bb7c-405e-9234-7524e58934d6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7e937d6c-ebdb-4e27-8b62-0e0252bfdf52 # iFrame
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28988636-846f-44b9-b489-ac19e4f8296a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1127d74d-ff73-4dba-b7cc-4f6d729c2877
        userCondition: null
group: null
groupChildBlockTypes: true
handle: iframe
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: iFrame
topLevel: true
