childBlocks: null
conditions: null
description: 'Copy and paste the embed code for your iframe.'
enabled: true
field: 612bfd79-519c-4db3-9ad9-3df56af2b354 # Landing Section
fieldLayouts:
  589e2536-e749-4f46-98e9-9e2a68dc39ce:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7e937d6c-ebdb-4e27-8b62-0e0252bfdf52 # iFrame
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f22dcfc9-836e-445f-bad4-f6ae1902367a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1b21694c-ce67-4b92-be7f-cd34b9f2ffb6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 917f53fa-1fa1-47af-8866-5b042d19b183 # Text Alignment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0339027-d681-4a90-ba54-b8a2db3cab8a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0fe7b501-d81b-44ac-9f5d-e7e3ba23600b # Max Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8fc6f589-adfe-46bf-b300-cc6ce155a05c
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: fc5d9a34-6e82-4a26-8f70-1bded3be9803
        userCondition: null
group: null
groupChildBlockTypes: true
handle: iframe
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 1
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: iFrame
topLevel: true
