childBlocks: null
conditions: null
description: ''
enabled: true
field: 537b387e-676e-45bc-8784-94ab111fecb8 # Series Landing Section
fieldLayouts:
  77657675-6911-4939-a05f-95d53041b947:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ef7ef68b-2072-4b19-835b-e2429a536f4f # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3bc86806-12e7-4931-bda6-0a1eb4ed018f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 35cd1418-9720-4759-99c9-ee3cadcae4eb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0fe7b501-d81b-44ac-9f5d-e7e3ba23600b # Max Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36a1553a-3fe6-4d18-8144-7dcef1176c56
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 4f6db3e0-7aa4-4d21-9b8b-de4a3f1eb3bd
        userCondition: null
group: null
groupChildBlockTypes: true
handle: image
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Image
topLevel: true
