childBlocks: null
conditions: null
description: 'Copy and paste the embed code for your lottie animation.'
enabled: true
field: 612bfd79-519c-4db3-9ad9-3df56af2b354 # Landing Section
fieldLayouts:
  589e2536-e749-4f46-98e9-9e2a68dc39ce:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7e937d6c-ebdb-4e27-8b62-0e0252bfdf52 # Lottie Animation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f22dcfc9-836e-445f-bad4-f6ae1902367a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1b21694c-ce67-4b92-be7f-cd34b9f2ffb6
        userCondition: null
group: null
groupChildBlockTypes: true
handle: lottieAnimation
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 1
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Lottie Animation'
topLevel: true
