childBlocks:
  - description
  - background
  - buttons
  - image
  - socialLinks
conditions: null
description: 'Add content to the card.'
enabled: true
field: 1d42debc-f311-4702-b75a-37951c101737 # Card Slider
fieldLayouts:
  1f7a3a2d-2ec1-4a98-91e8-602edc88b02a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8f9dcf6c-c14a-42d3-93aa-50bb7d29b35d # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dde73c70-42b9-4a38-aa15-9da590b60c04
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: d2646212-44e8-4021-8a5b-24f1b64eb1ef
        userCondition: null
group: null
groupChildBlockTypes: true
handle: slide
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Slide
topLevel: false
