fieldLayouts:
  4da69753-72fa-4eaf-b32e-f8a0fea3575a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 52aeef11-bc62-46d8-9c27-5292d9fca58e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 959bbb28-eea5-45c4-a652-04d40eea617b
        userCondition: null
fs: artistArt
handle: artistArt
name: 'Artist Art'
sortOrder: 12
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
