fieldLayouts:
  3a39a54b-dc4e-4106-acd4-e51da666b97c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: dd9cf869-419b-47ab-ab52-4178beb40695
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3d7ee51a-7d9d-43ce-951e-8d61188988fd
        userCondition: null
fs: backgroundImages
handle: backgroundImages
name: 'Background Images'
sortOrder: 7
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
