fieldLayouts:
  4d117a3f-509a-4cf8-9165-2caf302c6f08:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 0b1cdc94-9c67-4f96-9896-ce159b915f31
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 68a9255d-5554-4032-9ad1-b9863b027754
        userCondition: null
fs: characterArt
handle: characterArt
name: 'Character Art'
sortOrder: 6
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
