fieldLayouts:
  f7a22cf1-02b5-4279-9581-47d728113dec:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 2f15307d-8715-45c2-81d5-bf815af5051b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 166af22e-a65a-46be-90de-4b1f715e0ece
        userCondition: null
fs: generalImages
handle: generalImages
name: 'General Images'
sortOrder: 10
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
