fieldLayouts:
  d0d45e63-cc35-4d33-9b08-e86431baaa97:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 367b8a23-0ec7-45aa-a7e1-e757b9c260b8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 691bc211-50bf-4e5b-a0d0-34e6e86dd85c
        userCondition: null
fs: menus
handle: menus
name: Menus
sortOrder: 11
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
