fieldLayouts:
  1d8d18b0-23e1-4351-b02f-ce7764b8cec0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 9c662f71-58e8-48d2-90ae-a9a071836d67
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d3ad4cb7-72b1-476b-88e6-96a09977d2aa
        userCondition: null
fs: sixPacks
handle: sixPacks
name: 'Six Packs'
sortOrder: 13
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
