childBlocks: null
color: null
conditions: null
description: 'Add a background image or video. If you select a video, it will take precedence over the image and display instead.'
enabled: true
field: 612bfd79-519c-4db3-9ad9-3df56af2b354 # Landing Section
fieldLayouts:
  e24b7db2-bb87-446a-8e8b-7d4d88daa7b7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bffc7c3c-02c7-46d1-9835-a9096a16f727 # Background Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ccefdf4c-e395-4c9b-a5cf-8e6b3c018f70
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a11615b2-853a-4fe3-9dd7-99901084d23e # Background Video
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2782fbf6-2c11-440b-995e-501d634a5f3c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ddb79a7a-daff-4c9c-8a89-92f6d7dce4c7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 13504266-15af-46cc-abf9-80c9136fa83b # Background Overlay
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea5e27a9-1043-47e4-8582-732758b59300
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3c09f8e7-d651-4b43-9478-d543321de483 # Background Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5b6c27f-19f2-4190-9b57-d50f2ed9ef22
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d6f47149-cf68-4b22-9f64-4ea1bd5a7ee8 # Loop Video
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 699aa823-dd0d-4e33-80e5-dde6487dae85
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: a1de860d-8471-4129-9c66-120b944e4df3
        userCondition: null
group: null
groupChildBlockTypes: true
handle: background
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 1
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Background
topLevel: true
