childBlocks: null
conditions: null
description: ''
enabled: true
field: 1d42debc-f311-4702-b75a-37951c101737 # Card Slider
fieldLayouts:
  b9510581-fdd4-4d79-b78a-3b11f319ca2c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 021dc031-5726-4bf4-808e-53a9d3c50ab2 # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6bd77b46-6493-404c-adb3-f280d6d16def
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e3ecfd7a-7164-4c7f-ac96-c1bfd568fd45
        userCondition: null
group: null
groupChildBlockTypes: true
handle: buttons
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Buttons
topLevel: false
