childBlocks: null
color: null
conditions: null
description: ''
enabled: true
field: 612bfd79-519c-4db3-9ad9-3df56af2b354 # Landing Section
fieldLayouts:
  a802dc7d-7a88-4466-be8e-fa213c354b73:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ad02cc6a-65c1-461f-a44b-2675bdcd2625 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: efedd0a8-6d5b-4440-a4ac-230be4254757
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: feaff980-e795-49e9-ae40-58201c12003f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 917f53fa-1fa1-47af-8866-5b042d19b183 # Text Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6af4241-2b4c-4769-a6c3-d4920ca320dc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0fe7b501-d81b-44ac-9f5d-e7e3ba23600b # Max Width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db86d5c0-3f89-4a10-af81-4a7b598ae71a
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 3166a767-4077-4e14-a151-0380ba1a5a95
        userCondition: null
group: null
groupChildBlockTypes: true
handle: description
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Description
topLevel: true
