childBlocks:
  - description
  - background
  - buttons
conditions: null
description: 'Add content to the grid item.'
enabled: true
field: 10e9a8b2-c801-433b-82f1-4bfddf3231af # Page Sections
fieldLayouts:
  3fedba4a-f014-4e44-9a8c-2c9af7c487bb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8f9dcf6c-c14a-42d3-93aa-50bb7d29b35d # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dde73c70-42b9-4a38-aa15-9da590b60c04
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 249bfe0d-f012-4a7b-aafa-5e7dcbb632a1
        userCondition: null
group: null
groupChildBlockTypes: true
handle: gridItem
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Grid Item'
topLevel: false
