childBlocks: null
color: null
conditions: null
description: 'Copy and paste your iframe embed code.'
enabled: true
field: 612bfd79-519c-4db3-9ad9-3df56af2b354 # Landing Section
fieldLayouts:
  589e2536-e749-4f46-98e9-9e2a68dc39ce:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7e937d6c-ebdb-4e27-8b62-0e0252bfdf52 # iFrame
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f22dcfc9-836e-445f-bad4-f6ae1902367a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1b21694c-ce67-4b92-be7f-cd34b9f2ffb6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0fe7b501-d81b-44ac-9f5d-e7e3ba23600b # Max Width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9957660d-c4e3-46a2-94be-4c1c3091e5a6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 917f53fa-1fa1-47af-8866-5b042d19b183 # Text Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a07abeee-1b8b-4016-9935-d94936f992d1
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 2c64415e-6a4c-41f4-abf5-1d49b1d94345
        userCondition: null
group: null
groupChildBlockTypes: true
handle: iframe
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 1
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: iFrame
topLevel: true
