childBlocks: null
color: null
conditions: null
description: ''
enabled: true
field: 612bfd79-519c-4db3-9ad9-3df56af2b354 # Landing Section
fieldLayouts:
  c1e496fb-f279-43c6-b58c-99d5e39c7a3f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ef7ef68b-2072-4b19-835b-e2429a536f4f # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3bc86806-12e7-4931-bda6-0a1eb4ed018f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e5cfc9e9-b843-4db2-b209-03c8cbe0163c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0fe7b501-d81b-44ac-9f5d-e7e3ba23600b # Max Width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2167bc31-4a6d-4b2a-9a56-06cc12f0d8e6
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 1e468544-19a8-4a28-85dc-79edae1364bb
        userCondition: null
group: null
groupChildBlockTypes: true
handle: image
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Image
topLevel: true
