childBlocks: null
conditions: null
description: ''
enabled: true
field: 1d42debc-f311-4702-b75a-37951c101737 # Card Slider
fieldLayouts:
  6d7785ea-56ed-4eeb-b27a-72dfa719e8dd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ef7ef68b-2072-4b19-835b-e2429a536f4f # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aaa593ff-3f3c-4e2a-aa4f-3d6b0e9c733d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 59f2d432-57d8-47a9-ab5f-16c6061080d1
        userCondition: null
group: null
groupChildBlockTypes: true
handle: image
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Image
topLevel: false
