childBlocks: null
conditions: null
description: ''
enabled: true
field: 1d42debc-f311-4702-b75a-37951c101737 # Card Slider
fieldLayouts:
  b5ca0d79-508c-484c-93ff-e63fd1e0ad55:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8dbf61b7-8e71-4013-8e45-0e1e3f0d5922 # Social Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd41d220-2864-40f2-afc5-25936e976c55
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 38218369-ad96-4852-9f35-77a7c399cff6
        userCondition: null
group: null
groupChildBlockTypes: true
handle: socialLinks
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Social Links'
topLevel: false
