columnSuffix: livmsrlr
contentColumnType: char(7)
handle: accentColor
instructions: 'This is a small accent color found on many of our cans.'
name: 'Accent Color'
searchable: false
settings:
  defaultColor: '#ffffff'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
