columnSuffix: fzfkddjs
handle: awardName
instructions: 'What is the name of the award?'
name: 'Awards - Silver Award - Award Name'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: ''
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: null
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showHtmlButtonForNonAdmins: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
