columnSuffix: izbvksms
contentColumnType: string(7)
handle: backgroundSize
instructions: 'Choose a background-size rule for the image.'
name: 'Background Size'
searchable: false
settings:
  columnType: null
  options:
    -
      __assoc__:
        -
          - label
          - Contain
        -
          - value
          - contain
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Cover
        -
          - value
          - cover
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Auto
        -
          - value
          - auto
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 90%
        -
          - value
          - 90%
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
