columnSuffix: tumzrmaj
contentColumnType: char(7)
handle: backgroundColor
instructions: 'Choose a background color.'
name: 'Background Color'
searchable: false
settings:
  defaultColor: '#32373a'
  presets:
    - '#292f32'
    - '#32373a'
    - '#e9e9e9'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
