columnSuffix: nqxjvatg
handle: buttonText
instructions: 'Add text to the button.'
name: 'Buttons - Text Button - Button Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: Button
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
