columnSuffix: null
contentColumnType: string
handle: buttons
instructions: 'Add buttons to direct users.'
name: Buttons
searchable: false
settings:
  entryTypes:
    - 6f946d78-01c5-4036-b1bc-c43719d7b8de
    - 23d727ae-ebdd-4af8-8f61-bd7ebec87655
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
