columnSuffix: ydfukqvp
contentColumnType: char(7)
handle: darkColor
instructions: 'This is the dark color of the beer can.'
name: 'Dark Color'
searchable: false
settings:
  defaultColor: '#32373a'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
