columnSuffix: yjonfvze
contentColumnType: text
fieldGroup: 2123b6aa-6742-448c-95ac-70a91f1dfcef # General Fields
handle: description
instructions: 'Write a description.'
name: Description
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: ''
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: default.json
  removeEmptyTags: true
  removeInlineStyles: false
  removeNbsp: false
  showHtmlButtonForNonAdmins: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
