columnSuffix: lcuipune
contentColumnType: string
handle: headline
instructions: 'Write a title for this.'
name: Headline
searchable: false
settings:
  errorMessage: 'Unable to find component class ''craft\redactor\Field''.'
  expectedType: craft\redactor\Field
  settings:
    __assoc__:
      0:
        - availableTransforms
        - '*'
      1:
        - availableVolumes
        - ''
      2:
        - columnType
        - text
      3:
        - configSelectionMode
        - choose
      4:
        - defaultTransform
        - ''
      5:
        - manualConfig
        - ''
      7:
        - purifyHtml
        - true
      9:
        - removeEmptyTags
        - true
      10:
        - removeInlineStyles
        - false
      11:
        - removeNbsp
        - false
      12:
        - showHtmlButtonForNonAdmins
        - true
      13:
        - showUnpermittedFiles
        - false
      14:
        - showUnpermittedVolumes
        - false
      15:
        - uiMode
        - normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\MissingField
