columnSuffix: lcuipune
contentColumnType: text
fieldGroup: 2123b6aa-6742-448c-95ac-70a91f1dfcef # General Fields
handle: headline
instructions: 'Write a title for this.'
name: Headline
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: ''
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: null
  removeEmptyTags: true
  removeInlineStyles: false
  removeNbsp: false
  showHtmlButtonForNonAdmins: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
