columnSuffix: xcoxbybd
contentColumnType: char(7)
handle: lightColor
instructions: 'This is the light color of the beer can.'
name: 'Light Color'
searchable: false
settings:
  defaultColor: '#292f32'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
