columnSuffix: null
contentColumnType: string
fieldGroup: 2123b6aa-6742-448c-95ac-70a91f1dfcef # General Fields
handle: locationToggle
instructions: null
name: 'Location Toggle'
searchable: false
settings:
  maxBlocks: null
  maxLevels: null
  maxTopBlocks: null
  minBlocks: null
  minLevels: null
  minTopBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
