columnSuffix: unxlgmwp
contentColumnType: integer(10)
fieldGroup: 7376a32e-bb38-4467-b1b4-6e6db135167e # CSS Fields
handle: maxWidth
instructions: 'Define a max-width in pixels.'
name: 'Max Width'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: 0
  suffix: px
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
