columnSuffix: null
contentColumnType: string
handle: seriesLandingSection
instructions: null
name: 'Series Landing Section'
searchable: false
settings:
  errorMessage: 'Unable to find component class ''benf\neo\Field''.'
  expectedType: benf\neo\Field
  settings:
    __assoc__:
      6:
        - propagationMethod
        - all
translationKeyFormat: null
translationMethod: none
type: craft\fields\MissingField
