columnSuffix: null
contentColumnType: string
handle: socialLink
instructions: 'Paste the link and choose the corresponding channel.'
name: 'Social Link'
searchable: false
settings:
  entryTypes:
    - 2a66e961-61be-482a-b5c4-bd49a3747ea5
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
