columnSuffix: null
contentColumnType: string
fieldGroup: 2123b6aa-6742-448c-95ac-70a91f1dfcef # General Fields
handle: socialLink
instructions: 'Paste the link and choose the corresponding channel.'
name: 'Social Link'
searchable: false
settings:
  contentTable: '{{%matrixcontent_sociallink}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
