columnSuffix: sqskmytk
contentColumnType: string
handle: tastingNotes
instructions: 'What is the beer''s tasting notes?'
name: 'Tasting Notes'
searchable: true
settings:
  entryTypes:
    - 79759d1d-2122-469e-b071-f35ad6a27d0b
  maxEntries: 5
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
