dateModified: 1713389079
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: Channels
      type: heading
    -
      heading: Pages
      type: heading
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:ec54db85-dc39-4841-b6bc-17523b4d074d' # Beers
      tableAttributes:
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:76a1851c-73ea-4eb1-8e0d-a7501be656b0' # About
      tableAttributes:
        - postDate
        - expiryDate
        - author
        - link
      type: native
    -
      key: 'section:98a60530-1347-4020-a302-a11e470b343d' # Events
      type: native
    -
      key: 'section:1f34453a-cacc-4c27-a515-05b3a89f5b76' # Locations
      type: native
    -
      key: 'section:68810252-e0a1-46b8-9e77-0e47a057261b' # Pages
      type: native
email:
  fromEmail: ausbranham@gmail.com
  fromName: 'Melvin Brewing'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  artistArt:
    hasUrls: true
    name: 'Artist Art'
    settings:
      path: /images/artist-art
    type: craft\fs\Local
    url: '@web'
  backgroundImages:
    hasUrls: true
    name: 'Background Images'
    settings:
      path: '@webroot/images/background-images'
    type: craft\fs\Local
    url: /images/background-images
  backgroundVideos:
    hasUrls: true
    name: 'Background Videos'
    settings:
      path: '@webroot/videos/background-videos'
    type: craft\fs\Local
    url: /videos/background-videos
  canImages:
    hasUrls: true
    name: 'Can Images'
    settings:
      path: '@webroot/images/cans'
    type: craft\fs\Local
    url: /images/cans
  canVideos:
    hasUrls: true
    name: 'Can Videos'
    settings:
      path: '@webroot/videos/cans'
    type: craft\fs\Local
    url: /videos/cans
  characterArt:
    hasUrls: true
    name: 'Character Art'
    settings:
      path: '@webroot/images/character-art'
    type: craft\fs\Local
    url: /images/character-art
  generalImages:
    hasUrls: true
    name: 'General Images'
    settings:
      path: '@webroot/images/general-images'
    type: craft\fs\Local
    url: /images/general-images
  menus:
    hasUrls: true
    name: Menus
    settings:
      path: '@webroot/images/menus'
    type: craft\fs\Local
    url: /images/menus
  sixPacks:
    hasUrls: true
    name: 'Six Packs'
    settings:
      path: '@webroot/images/six-packs'
    type: craft\fs\Local
    url: /images/six-packs
meta:
  __names__:
    0fc8e255-72f1-47b9-bd76-88e28f794c33: Tagline # Tagline
    0fe7b501-d81b-44ac-9f5d-e7e3ba23600b: 'Max Width' # Max Width
    1d42debc-f311-4702-b75a-37951c101737: 'Card Slider' # Card Slider
    1f34453a-cacc-4c27-a515-05b3a89f5b76: Locations # Locations
    2a4d8edf-d2ca-4850-8d05-8dec0e8715ba: 'Dark Color' # Dark Color
    2f0eebdb-494a-4076-91e6-fba3c5059a2a: 'Beer Series' # Beer Series
    2f7552c2-f172-4dbb-b4f0-ff54cbff985d: Menu # Menu
    3c09f8e7-d651-4b43-9478-d543321de483: 'Background Size' # Background Size
    4abd99d6-2584-457d-b7c4-40f7b995e1c0: IBUs # IBUs
    4b4eed56-e5a2-41f4-b65c-26a8e0339e06: Hours # Hours
    5bde54d0-f163-4aff-82a7-fb8f3d0066a5: 'Background Images' # Background Images
    5f624c64-0bdb-4809-bbc7-8159ac90b16b: Home # Home
    6b38e3b8-9668-4a06-9898-2904d065930d: Headline # Headline
    6b810e20-091f-4ba9-a515-86143511bd1a: 'Release Date' # Release Date
    06f905a7-02ce-42c2-a7cc-ef21cf0c7559: 'Entry Field' # Entry Field
    7a9cb2ec-51b4-4eb8-821c-a1c35cdc2434: 'Can Image' # Can Image
    7b03dfd1-415d-4f52-abcc-c4d80fdf3331: 'Our Awards' # Our Awards
    7e937d6c-ebdb-4e27-8b62-0e0252bfdf52: iFrame # iFrame
    8c7ca72d-2bc1-4123-975e-84d0829fb82e: 'Artist Art' # Artist Art
    8dbf61b7-8e71-4013-8e45-0e1e3f0d5922: 'Social Link' # Social Link
    8de84d79-3354-4daf-955d-1b712c976678: 'Directions Description' # Directions Description
    8f9dcf6c-c14a-42d3-93aa-50bb7d29b35d: 'Background Color' # Background Color
    9c713e83-f0c5-4a2d-b111-e0ae67fa8153: Simple # Simple
    9f07dd88-6f43-4077-bdb0-cd92afabd6ad: 'Tap List' # Tap List
    9f5f0742-4deb-4408-a64a-f60a318f5e7e: Page # Page
    10e9a8b2-c801-433b-82f1-4bfddf3231af: 'Page Sections' # Page Sections
    12dfe028-e83e-4153-a5d8-6212d151b7e5: Directions # Directions
    021dc031-5726-4bf4-808e-53a9d3c50ab2: Buttons # Buttons
    25c6a98b-d119-4ae1-8d5f-e0a804ac1448: 'Series Toggle' # Series Toggle
    26df24ca-f2a9-40af-9c8a-01fb103c9b71: 'Beer Assets' # Beer Assets
    35d5050e-3d8c-448a-8ed5-1a9eaba13e13: 'Melvin Brewing' # Melvin Brewing
    44e811f6-d3d3-40d4-8ab8-c619a2ca9ed7: Sizes # Sizes
    47a2a87b-81e2-4dc8-8c48-9fe1c88ef5b2: Location # Location
    49ddd7e6-e7c8-4daa-9efc-c76341c5f129: 'Can Video' # Can Video
    55e9bc16-a0e6-4960-9a50-051e7b8c7dce: Style # Style
    76a1851c-73ea-4eb1-8e0d-a7501be656b0: About # About
    76d8c99d-22ff-41b1-a339-bcd4431c4457: 'Six Packs' # Six Packs
    76d72b7b-bcd8-4f9a-807e-905a9c11c83e: 'Can Images' # Can Images
    81a24339-11e3-4828-9bb5-f5db1693d5a4: 'Individual Beer' # Individual Beer
    98a60530-1347-4020-a302-a11e470b343d: Events # Events
    537b387e-676e-45bc-8784-94ab111fecb8: 'Series Landing Section' # Series Landing Section
    612bfd79-519c-4db3-9ad9-3df56af2b354: 'Landing Section' # Landing Section
    917f53fa-1fa1-47af-8866-5b042d19b183: 'Text Alignment' # Text Alignment
    1777ecad-74d3-487a-bfa0-01bcdbb8654a: Footer # Footer
    2382eb8f-094b-419b-9d10-9646b6a08d24: 'Lifestyle Images' # Lifestyle Images
    04064be6-a1dd-4ced-87d6-df11aec37a6d: 'Beer Story' # Beer Story
    4169ea13-b47e-4db2-a7bc-7c20b7a9a017: Description # Description
    8096c7d3-a86e-4f8a-918e-b35d8071e1b5: 300x300 # 300x300
    31803f1b-64e4-4e43-84c2-e2b426caa398: 'Our Approach' # Our Approach
    33276f80-27b6-498b-af0c-9b2fecae98db: 'Entry Field' # Entry Field
    43882e81-bc87-43ff-9313-d303783fa479: Default # Default
    91292bbe-c31e-4eec-ab7b-920070a37071: Background # Background
    5626309f-5327-4844-a153-344a113be872: 'Location Toggle' # Location Toggle
    7106060e-2428-41c0-86c7-cd3cc951b8d5: Menus # Menus
    13504266-15af-46cc-abf9-80c9136fa83b: 'Background Overlay' # Background Overlay
    24191240-8b69-49ba-8827-7ce1b93a9d92: Background # Background
    68810252-e0a1-46b8-9e77-0e47a057261b: Pages # Pages
    a20ccb00-5af6-453c-bd60-33cdd94bd258: Description # Description
    a111ef49-544a-4868-b0aa-c9f69bffffd1: Height # Height
    a170e21e-70f6-4e9c-81d8-75c1f5a49066: Description # Description
    a11615b2-853a-4fe3-9dd7-99901084d23e: 'Background Video' # Background Video
    a5788732-8476-446d-b6ed-04f8cc7d9c00: Awards # Awards
    ad02cc6a-65c1-461f-a44b-2675bdcd2625: Description # Description
    b06f7d5b-f09a-4ddf-b77f-dc89f56a7419: 'Background Videos' # Background Videos
    b51eebcc-49ce-435f-aaae-9ee29609d1cd: 'Character Art' # Character Art
    b4618125-57d2-42f8-baa9-39c59d55e4b9: Buttons # Buttons
    bffc7c3c-02c7-46d1-9835-a9096a16f727: 'Background Image' # Background Image
    c002a262-f5da-4752-8558-84317e52ce18: 'Featured Beer' # Featured Beer
    c0486f15-08b3-4340-85af-cc6145d544fb: Image # Image
    c489ee54-b601-4a10-b8c9-2819a6d179e3: Header # Header
    d6f47149-cf68-4b22-9f64-4ea1bd5a7ee8: 'Loop Video' # Loop Video
    d65d412c-37d7-40cd-b379-d7b6d0a20a45: 'Tasting Notes' # Tasting Notes
    d576e14e-afd8-482e-9c41-2c24b7f4c69b: iFrame # iFrame
    d9712e97-c935-48f3-8b44-f3ce6e52d842: 'Melvin Brewing' # Melvin Brewing
    d16669bc-8ed5-462f-9d01-7d54f2d6bf4b: 'Twelve oz Can' # Twelve oz Can
    db8abdd9-1020-4ad6-ae82-52f60e337a94: 'Alcohol Content' # Alcohol Content
    db9d70f0-8392-4fbe-801f-9deeb6f7a968: 'General Images' # General Images
    dbe83280-d2a8-44af-8699-24516dc89a1f: Entry # Entry
    dca70112-408c-40db-980b-dbdbbee87ca8: 'Can Videos' # Can Videos
    dee2939b-bc5f-4150-9d53-4c6cfd58cc02: Awards # Awards
    e9dbc6a8-c947-4769-887a-b8e7d205a8d7: 'Character Art' # Character Art
    eb65a6c5-a692-4ead-997b-adef82b174cd: 'Light Color' # Light Color
    ec54db85-dc39-4841-b6bc-17523b4d074d: Beers # Beers
    edf1bec9-a1e3-47ea-beab-3c17e1cc133e: 'Accent Color' # Accent Color
    ef7ef68b-2072-4b19-835b-e2429a536f4f: Image # Image
    f72f22c2-cd1f-412b-8d4c-b83e4514b948: 'Our Artists' # Our Artists
    f649f3ae-9db1-4aeb-a850-3977f5bc45ff: 'Six Pack' # Six Pack
    fab91d94-7ec6-4694-80f5-f8da8ac5a47d: 'Public Schema' # Public Schema
    fd3723f7-ae7c-4ae3-ae60-3e2044f82fac: 'Background Navigation' # Background Navigation
    fdb4b497-cc54-40da-b81e-d107903c5bc6: 'Our Story' # Our Story
plugins:
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      cpSectionEnabled: true
  image-toolbox:
    edition: lite
    enabled: true
    licenseKey: 0GYYCQN4XZPF0OB7HS3ANP1H
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: SJ2E01DJNYRYJIR1016SZOBQ
    schemaVersion: 2.1.0
  neo:
    edition: standard
    enabled: true
    licenseKey: 8R7J6CL3XMZ72TGUTKMGT3VS
    schemaVersion: 5.0.0.1
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: LJW88RX1V7BBQB200N3BW540
    schemaVersion: 3.0.12
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      alwaysIncludeCanonicalUrls: false
      cpTitlePrefix: '⚙ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - '''self'''
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableDebugToolbarPanel: true
      enableJsonLdEndpoint: false
      enableMetaContainerEndpoint: false
      enableSeoFileLinkEndpoint: false
      environment: local
      excludeNonCanonicalUrls: false
      generatorEnabled: true
      headersEnabled: true
      includeHomepageInBreadcrumbs: true
      lowercaseCanonicalUrl: true
      manuallySetEnvironment: true
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 0
      pluginName: SEOmatic
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: true
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
      truncateDescriptionTags: true
      truncateTitleTags: true
system:
  edition: pro
  live: true
  name: 'Melvin Brewing'
  retryDuration: null
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
