defaultPlacement: end
enableVersioning: true
entryTypes:
  - 7b03dfd1-415d-4f52-abcc-c4d80fdf3331 # Our Awards
  - 31803f1b-64e4-4e43-84c2-e2b426caa398 # Our Approach
  - f72f22c2-cd1f-412b-8d4c-b83e4514b948 # Our Artists
  - fdb4b497-cc54-40da-b81e-d107903c5bc6 # Our Story
handle: about
name: About
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  35d5050e-3d8c-448a-8ed5-1a9eaba13e13: # Melvin Brewing
    enabledByDefault: true
    hasUrls: true
    template: _about/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 03322b05-3e82-48d1-a93d-1838c1c0b3b9
type: structure
