defaultPlacement: end
enableVersioning: true
entryTypes:
  - 43882e81-bc87-43ff-9313-d303783fa479 # Default
handle: events
name: Events
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  35d5050e-3d8c-448a-8ed5-1a9eaba13e13: # Melvin Brewing
    enabledByDefault: true
    hasUrls: true
    template: _events/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 1acae557-b0d2-44f1-a96c-1fb1404afc18
type: structure
